all:
	ipython contourplots.py ../../docs/figs/
	ipython objectivecomp.py ../../docs/figs/
	ipython print_sens.py ../../docs/figs/
	ipython solarlat.py ../../docs/figs/
	ipython windstruct.py ../../docs/figs/
	ipython battsolarcon.py ../../docs/figs/

