all:
	pdflatex papersingle.tex
	bibtex papersingle.aux
	pdflatex papersingle.tex
	pdflatex papersingle.tex
	pdflatex paperdouble.tex
	bibtex paperdouble.aux
	pdflatex paperdouble.tex
	pdflatex paperdouble.tex
	pdflatex papersingledraft.tex
	bibtex papersingledraft.aux 
	pdflatex papersingledraft.tex
	pdflatex papersingledraft.tex
	pdflatex papernonaiaa.tex
	bibtex papernonaiaa.aux
	pdflatex papernonaiaa.tex
	pdflatex papernonaiaa.tex
	pdflatex presentation.tex
